spring:
  datasource:
    # PG 连接串：建议显式加上 ?currentSchema=public，防止找不到表
    url: jdbc:postgresql://localhost:5432/new-exam?stringtype=unspecified&currentSchema=public
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  application:
    name: ai-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  ai:
    retry:
      enabled: false  # 禁用自动重试
    zhipuai:
      api-key: b018802065574260ae4463ecc9ad872e.FPyHyG5R8n4GKGUu
      embedding:
        options:
          model: embedding-3
          dimensions: 256

    vectorstore:
      redis:
        url: redis://localhost:6378  # 某些版本的 Spring AI 可能需要显式配置 URI
        #        indexName: my-vector-index
        indexName: exam
        prefix: "doc:"
        initialize-schema: true


    ollama:
      base-url: http://localhost:11434
      read-timeout: 120s

      chat:
        model: qwen3:4b
        options:
          temperature: 0.7
      embedding:
        model: embeddinggemma:latest

server:
  port: 7055
  servlet:
    context-path: /ai


mybatis-plus:
  # 1. 映射文件位置 (如果你需要写手写 XML SQL)
  mapper-locations: classpath*:/mapper/**/*.xml

  # 2. 配置策略
  configuration:
    # 开启 SQL 日志打印 (开发环境必开，方便调试)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动将下划线转驼峰 (user_name -> userName)，默认就是 true
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      # 3. 主键策略 (非常重要，见下文详细解释)
      # 如果你的 PG 表主键是 SERIAL/BIGSERIAL (自增)，用 AUTO
      # 如果你想用 MP 自带的雪花算法 (分布式ID)，用 ASSIGN_ID
      id-type: auto


redis-stack:
  port: 6378
